### ISSUE TITLE
 https://winget.run/ is not updating automatically 

### ISSUE THREAD

**Issue by DW-42** [winget-run/api#131]
It would seem that since the winget manifest file specification changed to version 1.0 the website https://winget.run/ is not updating automatically. It could be coincidence, but I assume is because the api cannot parse the new file format correctly.  

- [https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md](url)

**Comment by Dragon1320** [comment]
All the back-end work for that has been done, we just need to deploy the changes. I'll get to that part either later today or tomorrow.

**Comment by DW-42** [comment]
The website ( https://winget.run/ ) is still broken. :-(

**Comment by Dragon1320** [comment]
I'll try to get it fixed as soon as I can (I wanna say around 1-2 weeks), just happens that I've been busy with work lately and haven't had much time to do much.

**Comment by yoshiask** [comment]
Is this issue going to be resolved soon? I noticed the same issue with `GitHub.GitHubDesktop`: the reported version is 2.6.6, but the latest is 2.9.5.

**Comment by Dragon1320** [comment]
Everything should be updated now. There may be some small issues like a couple missing versions and fields but I'll try to fix those over the next couple weeks.
