### ISSUE TITLE
Any examples of how to write it?

### ISSUE THREAD

**Issue by wonkyungup** [winget-run/api#166]
https://api.winget.run/v2/packages/ 

What else should I write on the back?

**Comment by peacemaker360** [comment]
For me it is working with `/{publisher}/{packageName}` eg `https://api.winget.run/v2/packages/Google/Chrome` => Should return Google Chrome app.

Docs: https://docs.winget.run/docs/packages#single-package

**Comment by wonkyungup** [comment]
https://api.winget.run/v2/packages/NetSarangComputer/PortX

@peacemaker360
The latest version is 2.0.12, why is it coming out as 2.0.3?

**Comment by peacemaker360** [comment]
@wonkyungup something I discovered as well with other packages. The winget.run API seems to have stopped, at some point,  populating the latest manifest from the official source.
Couldn't figure out why. I guess we have to wait for the devs to have a look at this.
In the meantime you may still use winget, as it delivers the most recent versions.

**Comment by wonkyungup** [comment]
@peacemaker360 ok thanks for your help.
All questions have been answered, so I will close the branch.  Thanks for the details
